export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_PRODUCT_BY_SLUG = "FETCH_PRODUCT_BY_SLUG";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const INCREASE_PRODUCT_COUNT = "INCREASE_PRODUCT_COUNT";
export const DECREASE_PRODUCT_COUNT = "DECREASE_PRODUCT_COUNT";
export const ORDER_PRODUCT_BY_PRICE = "ORDER_PRODUCT_BY_PRICE";